# Generated by Django 2.2.6 on 2020-08-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, upload_to='photo')),
                ('description', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter_app.AnimalType', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
