# Generated by Django 2.2.6 on 2020-08-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='type',
            new_name='animal_type',
        ),
    ]
