# Generated by Django 2.2.6 on 2020-08-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0002_auto_20200808_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Вид животного', 'verbose_name_plural': 'Виды животных'},
        ),
    ]
