# Generated by Django 2.2.6 on 2020-08-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0004_auto_20200808_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrated',
            field=models.IntegerField(choices=[(1, 'да'), (0, 'нет')], default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
    ]
