# Generated by Django 2.2.6 on 2020-08-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0005_auto_20200809_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrated',
            field=models.IntegerField(choices=[('да', 'да'), ('нет', 'нет')], default='нет'),
        ),
    ]
