# Generated by Django 2.2.6 on 2020-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0006_auto_20200809_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrated',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3),
        ),
    ]
