# Generated by Django 2.2.6 on 2020-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0007_auto_20200809_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('мальчик', 'мальчик'), ('девочка', 'девочка')], default='мальчик', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinated',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3, verbose_name='Прививки'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='castrated',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3, verbose_name='Катрирован/старилизована'),
        ),
    ]
